# -*- coding: utf-8 -*-
"""analytics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgh7ELgwtytaOfGZx2ZrPdwBOEJtK5lz
"""

#++++++++++++++++++++++++ANALYTICS++++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
import os
import sys
import time
import pandas as pd
import psycopg2
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime

# ── config ─────────────────────────────────────────────────────────────────────
DB_URL              = os.environ.get("NEON_CONNECTION_STRING", "")
SERVICE_ACCOUNT_JSON = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "")

SCOPES = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]

# ── connections ────────────────────────────────────────────────────────────────

def get_conn():
    return psycopg2.connect(DB_URL)

def get_gspread():
    import json, tempfile
    creds_dict = json.loads(SERVICE_ACCOUNT_JSON)
    creds = Credentials.from_service_account_info(creds_dict, scopes=SCOPES)
    return gspread.authorize(creds)

# ── helpers ────────────────────────────────────────────────────────────────────

def push(sh, worksheet_name, df, sleep=2):
    """Clear and update a worksheet with a dataframe."""
    ws = sh.worksheet(worksheet_name)
    ws.clear()
    ws.update([df.columns.tolist()] + df.values.tolist())
    time.sleep(sleep)

def run_query(conn, query):
    return pd.read_sql(query, conn)

# ── queries ────────────────────────────────────────────────────────────────────

def run_analytics():
    conn = get_conn()
    gc   = get_gspread()
    sh   = gc.open("charts_engage")

    # 1. Subscriber count by channel
    df = run_query(conn, """
        SELECT name, category, subscribers FROM channels
        ORDER BY category
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "subscribers", df)

    # 2. Total views by channel in the previous 30 days
    df = run_query(conn, """
        SELECT c.name, c.category, SUM(v.views) AS total_views
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere', 'livestream')
        GROUP BY c.category, c.name
        ORDER BY SUM(v.views) DESC
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "total_views", df)

    # 3. Top 5 videos across all channels
    df = run_query(conn, """
        SELECT v.title, c.name, v.views FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.content_type NOT IN ('broadcast_archive', 'live_or_premiere', 'livestream')
        ORDER BY v.views DESC
        LIMIT 5
    """)
    df.columns = df.columns.str.upper()
    push(sh, "Top_5_videos", df)

    # 4. Average videos published per active day per channel
    df = run_query(conn, """
        SELECT name, category,
               ROUND(CAST(total_videos AS NUMERIC) / active_days, 0) AS videos_published_per_active_day
        FROM (
            SELECT c.name, c.category,
                   COUNT(v.video_id) AS total_videos,
                   COUNT(DISTINCT DATE(v.published_at)) AS active_days
            FROM videos v
            JOIN channels c ON v.channel_id = c.channel_id
            WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
            AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere', 'livestream')
            GROUP BY c.category, c.name
        ) sub
        ORDER BY videos_published_per_active_day DESC
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "videos_per_day", df)

    # 5. Posting time of videos by category (IST hour)
    df = run_query(conn, """
        SELECT
            c.category,
            EXTRACT(HOUR FROM (v.published_at AT TIME ZONE 'UTC' AT TIME ZONE 'Asia/Kolkata'))::INTEGER AS published_at_hour_ist,
            COUNT(v.video_id) AS videos_published,
            SUM(COUNT(v.video_id)) OVER (PARTITION BY c.category) AS category_total,
            ROUND(100.0 * COUNT(v.video_id) / SUM(COUNT(v.video_id)) OVER (PARTITION BY c.category), 2) AS pct
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere', 'livestream')
        GROUP BY c.category, published_at_hour_ist
        ORDER BY c.category, published_at_hour_ist
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "posting_time_of_videos", df)

    # 6. Content type distribution by category
    df = run_query(conn, """
        SELECT
            c.category,
            v.content_type,
            COUNT(v.video_id) AS videos_published,
            SUM(COUNT(v.video_id)) OVER (PARTITION BY c.category) AS category_total,
            ROUND(100.0 * COUNT(v.video_id) / SUM(COUNT(v.video_id)) OVER (PARTITION BY c.category), 2) AS pct
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        GROUP BY c.category, v.content_type
        ORDER BY c.category, videos_published DESC
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "duration_of_videos", df)

    # 7. Engagement score by channel
    df = run_query(conn, """
        SELECT c.name, c.category, COUNT(DISTINCT v.video_id) AS total_videos,
               ROUND(((SUM(v.likes) * 3.0) + (SUM(v.comments) * 1.0)) * 100.0 / NULLIF(SUM(v.views), 0), 2) AS engagement_score
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere', 'livestream')
        GROUP BY c.name, c.category
        ORDER BY engagement_score DESC
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "engagement_score", df)

    # 8. Views per hour vs volume by channel
    df = run_query(conn, """
        SELECT
            c.name,
            c.category,
            COUNT(DISTINCT v.video_id) AS total_videos,
            SUM(v.views) AS total_views,
            ROUND(
                SUM(v.views) * 1.0 / NULLIF(
                    SUM(EXTRACT(EPOCH FROM (NOW() - v.published_at)) / 3600), 0
                ), 4
            ) AS vph
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere', 'livestream')
        GROUP BY c.name, c.category
        ORDER BY vph DESC
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "vph_vs_volume", df)

    # 9. Engagement score vs volume
    df = run_query(conn, """
        SELECT c.name, c.category, COUNT(DISTINCT v.video_id) AS total_videos,
               ROUND(((SUM(v.likes) * 3.0) + (SUM(v.comments) * 1.0)) * 100.0 / NULLIF(SUM(v.views), 0), 2) AS engagement_score
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere', 'livestream')
        GROUP BY c.name, c.category
        ORDER BY c.category
    """)
    df["category"] = df["category"].str.upper()
    push(sh, "eng_scr_vs_vol", df)

    # 10. Editorial effort by channel (regular videos only, split by category)
    df = run_query(conn, """
        SELECT
            c.name,
            c.category,
            COUNT(DISTINCT v.video_id) AS total_videos,
            ROUND(SUM(v.duration_seconds) / 3600.0, 1) AS total_hours
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type = 'regular'
        GROUP BY c.channel_id, c.name, c.category
    """)
    df["category"] = df["category"].str.upper()

    category_sheet_map = {
        "WEB-ONLY":   "editorial_effort_web",
        "PRINT":      "editorial_effort_print",
        "TELEVISION": "editorial_effort_tv",
    }

    for category, sheet_name in category_sheet_map.items():
        cat_df = df[df["category"] == category].copy()

        cat_df["z_videos"] = (
            (cat_df["total_videos"] - cat_df["total_videos"].mean()) /
            cat_df["total_videos"].std(ddof=1)
        ).round(4)

        cat_df["z_hours"] = (
            (cat_df["total_hours"] - cat_df["total_hours"].mean()) /
            cat_df["total_hours"].std(ddof=1)
        ).round(4)

        cat_df["editorial_effort"] = (cat_df["z_videos"] + cat_df["z_hours"]).round(4)

        try:
            ws = sh.worksheet(sheet_name)
        except gspread.WorksheetNotFound:
            ws = sh.add_worksheet(title=sheet_name, rows=50, cols=10)

        ws.clear()
        ws.update([cat_df.columns.tolist()] + cat_df.values.tolist())
        time.sleep(5)



    # 11. Views distribution by duration_bucket per channel
    df = run_query(conn, """
        SELECT
            (c.name || '-VIEWS') AS "channel-views",
            v.duration_bucket as duration_bucket_views,
            SUM(v.views) AS total_views,
            ROUND(100.0 * SUM(v.views) / SUM(SUM(v.views)) OVER (PARTITION BY c.name), 2) AS pct_views,
            ' ' AS spacer,
            (c.name || '-VIDEOS') AS "channel-videos",
            v.duration_bucket as duration_bucket_videos,
            COUNT(v.video_id) AS total_videos,
            ROUND(100.0 * COUNT(v.video_id) / SUM(COUNT(v.video_id)) OVER (PARTITION BY c.name), 2) AS pct_videos
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere')
        GROUP BY c.name, c.category, v.duration_bucket
        ORDER BY c.category, c.name,
            CASE v.duration_bucket
                WHEN 'livestream'  THEN 6
                WHEN '30-60 min'   THEN 5
                WHEN '15-30 min'   THEN 4
                WHEN '5-15 min'    THEN 3
                WHEN '1-5 min'     THEN 2
                WHEN 'short'       THEN 1
            END DESC
    """)
    push(sh, "views_by_duration_channel", df)
    
    # 12. Views distribution by duration_bucket per segment
    df1 = run_query(conn, """
        SELECT
        CASE c.category
            WHEN 'print'      THEN 'PRINT-VIEWS'
            WHEN 'web-only'   THEN 'WEB-ONLY-VIEWS'
            WHEN 'television' THEN 'TELEVISION-VIEWS'
        END AS "category-views-videos",
        c.category,
        v.duration_bucket as duration_bucket_views_videos,
        SUM(v.views) AS total_views_videos,
        ROUND(100.0 * SUM(v.views) / SUM(SUM(v.views)) OVER (PARTITION BY c.category), 2) AS pct_views_videos
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere')
        GROUP BY c.category, v.duration_bucket
        ORDER BY c.category,
        CASE v.duration_bucket
            WHEN 'livestream'  THEN 6
            WHEN '30-60 min'   THEN 5
            WHEN '15-30 min'   THEN 4
            WHEN '5-15 min'    THEN 3
            WHEN '1-5 min'     THEN 2
            WHEN 'short'       THEN 1
        END DESC
    """)

    df2 = run_query(conn, """
        SELECT
        CASE c.category
            WHEN 'print'      THEN 'PRINT-VIDEOS'
            WHEN 'web-only'   THEN 'WEB-ONLY-VIDEOS'
            WHEN 'television' THEN 'TELEVISION-VIDEOS'
        END AS "category-views-videos",
        c.category,
        v.duration_bucket as duration_bucket_views_videos,
        COUNT(v.video_id) AS total_views_videos,
        ROUND(100.0 * COUNT(v.video_id) / SUM(COUNT(v.video_id)) OVER (PARTITION BY c.category), 2) AS pct_views_videos
        FROM videos v
        JOIN channels c ON v.channel_id = c.channel_id
        WHERE v.published_at BETWEEN NOW() - INTERVAL '31 days' AND NOW() - INTERVAL '1 day'
        AND v.content_type NOT IN ('broadcast_archive', 'live_or_premiere')
        GROUP BY c.category, v.duration_bucket
        ORDER BY c.category,
        CASE v.duration_bucket
            WHEN 'livestream'  THEN 6
            WHEN '30-60 min'   THEN 5
            WHEN '15-30 min'   THEN 4
            WHEN '5-15 min'    THEN 3
            WHEN '1-5 min'     THEN 2
            WHEN 'short'       THEN 1
        END DESC
    """)
    df=pd.concat([df1, df2], ignore_index=True)
    push(sh, "views_by_duration_segment", df)
    conn.close()
    print(f"✓ analytics.py completed at {datetime.now().strftime('%d %b %Y, %I:%M %p')}")

def run_backup():
    """Copy charts_engage → yesterday_analytics. Run manually after visual check."""
    gc     = get_gspread()
    source = gc.open("charts_engage")
    backup = gc.open("yesterday_analytics")

    tabs = [
        "subscribers", "total_views", "Top_5_videos",
        "videos_per_day", "posting_time_of_videos", "duration_of_videos",
        "engagement_score", "vph_vs_volume", "eng_scr_vs_vol",
        "editorial_effort_web", "editorial_effort_tv", "editorial_effort_print", "views_by_duration_channel", "views_by_duration_segment"
    ]

    for tab in tabs:
        data = source.worksheet(tab).get_all_values()
        ws   = backup.worksheet(tab)
        ws.clear()
        ws.update(data)
        print(f"✓ {tab}")
        time.sleep(3)

    print("\nBackup complete.")


if __name__ == "__main__":
    run_analytics()
