# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgh7ELgwtytaOfGZx2ZrPdwBOEJtK5lz
"""

#+++++++++++++++++++++++++++++FETCH+++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
import os
import re
import time
from datetime import datetime, timedelta, timezone

import psycopg2
from psycopg2.extras import execute_values
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# ── config ─────────────────────────────────────────────────────────────────────
API_KEY       = os.environ.get("YOUTUBE_API_KEY", "")
DB_URL        = os.environ.get("NEON_CONNECTION_STRING", "")
LOOKBACK_DAYS = 30

IST_OFFSET   = timezone(timedelta(hours=5, minutes=30))
CAPTURE_HOUR = 12  # 12:00 PM IST

# ── youtube client ─────────────────────────────────────────────────────────────
youtube = build("youtube", "v3", developerKey=API_KEY)

# ── helpers ────────────────────────────────────────────────────────────────────

def parse_duration(iso_duration):
    if not iso_duration or iso_duration in ("P0D", "PT0S", ""):
        return 0
    match = re.match(r'P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?', iso_duration)
    if not match:
        print(f"    [WARN] Unparseable duration: {iso_duration!r}")
        return 0
    days    = int(match.group(1) or 0)
    hours   = int(match.group(2) or 0)
    minutes = int(match.group(3) or 0)
    seconds = int(match.group(4) or 0)
    return days * 86400 + hours * 3600 + minutes * 60 + seconds


def detect_language(title):
    for char in title:
        cp = ord(char)
        if 0x0900 <= cp <= 0x097F:
            return "hi"
        if 0x0B80 <= cp <= 0x0BFF:
            return "ta"
    return "en"


def classify_content_type(duration_sec):
    if duration_sec == 0:
        return "live_or_premiere"
    elif duration_sec <= 60:
        return "short"
    elif duration_sec > 14400:
        return "broadcast_archive"
    elif duration_sec > 3600:
        return "livestream"
    else:
        return "regular"
def classify_duration_bucket(duration_sec):
    if duration_sec == 0:
        return "live or premiere"
    elif duration_sec <= 60:
        return "short"
    elif duration_sec <= 300:
        return "1-5 min"
    elif duration_sec <= 900:
        return "5-15 min"
    elif duration_sec <= 1800:
        return "15-30 min"
    elif duration_sec <= 3600:
        return "30-60 min"
    elif duration_sec <= 14400:
        return "livestream"
    else:
        return "broadcast archive"

def compute_views_per_hour(views, published_at):
    now       = datetime.now(timezone.utc)
    published = datetime.fromisoformat(published_at.replace("Z", "+00:00"))
    hours_live = max((now - published).total_seconds() / 3600, 1)
    return round(views / hours_live, 4)


def compute_engagement_score(likes, comments, views):
    return round(likes * 1.0 + comments * 0.75 + views * 0.5, 4)


# ── fetch logic ────────────────────────────────────────────────────────────────

def get_channel_videos(channel_id, published_after_dt, published_before_dt):
    playlist_id = "UU" + channel_id[2:]
    video_ids   = []
    next_page   = None

    while True:
        response = youtube.playlistItems().list(
            part       = "contentDetails",
            playlistId = playlist_id,
            maxResults = 50,
            pageToken  = next_page
        ).execute()

        for item in response.get("items", []):
            published_raw = item["contentDetails"].get("videoPublishedAt")
            if not published_raw:
                continue
            published_dt = datetime.fromisoformat(published_raw.replace("Z", "+00:00"))
            if published_dt >= published_before_dt:
                continue
            if published_dt < published_after_dt:
                return video_ids
            video_ids.append(item["contentDetails"]["videoId"])

        next_page = response.get("nextPageToken")
        if not next_page:
            break

    return video_ids


def get_video_details(video_ids):
    results = []
    for i in range(0, len(video_ids), 50):
        batch    = video_ids[i:i+50]
        response = youtube.videos().list(
            part = "snippet,contentDetails,statistics",
            id   = ",".join(batch)
        ).execute()
        results.extend(response.get("items", []))
    return results


# ── database writes ────────────────────────────────────────────────────────────

def batch_upsert_videos(cur, items, channel_category):
    """Batch insert all video rows — ON CONFLICT DO NOTHING handles dedup."""
    rows = []
    for item in items:
        snippet      = item["snippet"]
        details      = item["contentDetails"]
        duration_sec = parse_duration(details.get("duration", ""))
        rows.append((
            item["id"],
            snippet["channelId"],
            snippet["title"],
            snippet["publishedAt"],
            duration_sec,
            channel_category,
            detect_language(snippet["title"]),
            classify_content_type(duration_sec),
            classify_duration_bucket(duration_sec),
        ))
    execute_values(cur, """
        INSERT INTO videos
            (video_id, channel_id, title, published_at,
             duration_seconds, category, language, content_type,
             duration_bucket)
        VALUES %s
        ON CONFLICT (video_id) DO NOTHING
    """, rows)


def batch_insert_snapshots(cur, items, fetched_on):
    """Batch insert all snapshot rows for the channel in one DB call."""
    rows = []
    for item in items:
        stats    = item.get("statistics", {})
        views    = int(stats.get("viewCount",    0))
        likes    = int(stats.get("likeCount",    0))
        comments = int(stats.get("commentCount", 0))

        published_at      = item["snippet"]["publishedAt"]
        vph               = compute_views_per_hour(views, published_at)
        eng               = compute_engagement_score(likes, comments, views)
        interaction_score = round(likes * 1.0 + comments * 2.0, 4)
        engagement_rate   = round((likes + comments) / views * 100, 6) if views >= 1000 else None
        snapshot_id       = f"{item['id']}_{fetched_on}"

        rows.append((
            snapshot_id, item["id"], fetched_on,
            views, likes, comments,
            vph, eng,
            interaction_score, engagement_rate
        ))

    execute_values(cur, """
        INSERT INTO video_snapshots
            (snapshot_id, video_id, fetched_on,
             views, likes, comments,
             views_per_hour, engagement_score,
             interaction_score, engagement_rate)
        VALUES %s
        ON CONFLICT (snapshot_id) DO NOTHING
    """, rows)


# ── subscriber update ──────────────────────────────────────────────────────────

def update_subscriber_counts(conn):
    cur = conn.cursor()
    cur.execute("SELECT channel_id FROM channels")
    channel_ids = [r[0] for r in cur.fetchall()]

    for i in range(0, len(channel_ids), 50):
        batch    = channel_ids[i:i+50]
        response = youtube.channels().list(part="statistics", id=",".join(batch)).execute()
        for item in response.get("items", []):
            subs = int(item["statistics"].get("subscriberCount", 0))
            cur.execute(
                "UPDATE channels SET subscribers = %s WHERE channel_id = %s",
                (subs, item["id"])
            )

    conn.commit()
    cur.close()
    print("Subscriber counts updated.")


# ── main ───────────────────────────────────────────────────────────────────────

def run_fetch():
    conn = psycopg2.connect(DB_URL)
    cur  = conn.cursor()

    now_ist    = datetime.now(IST_OFFSET)
    noon_today = now_ist.replace(hour=CAPTURE_HOUR, minute=0, second=0, microsecond=0)

    published_before_dt = noon_today - timedelta(days=1)
    published_after_dt  = published_before_dt - timedelta(days=LOOKBACK_DAYS)
    fetched_on          = now_ist.date().isoformat()

    print(f"Fetch window : {published_after_dt.isoformat()} → {published_before_dt.isoformat()}")
    print(f"Fetched on   : {fetched_on}\n")

    cur.execute("SELECT channel_id, name, category FROM channels")
    channels = cur.fetchall()

    total_videos    = 0
    total_snapshots = 0

    for channel_id, name, category in channels:
        print(f"→ {name} ({category})", end=" ... ", flush=True)
        t0 = time.time()

        try:
            video_ids = get_channel_videos(channel_id, published_after_dt, published_before_dt)

            if not video_ids:
                print("0 videos")
                continue

            details = get_video_details(video_ids)

            batch_upsert_videos(cur, details, category)
            batch_insert_snapshots(cur, details, fetched_on)
            conn.commit()

            elapsed = round(time.time() - t0, 1)
            print(f"{len(details)} videos — {elapsed}s")

            total_videos    += len(details)
            total_snapshots += len(details)

        except HttpError as e:
            print(f"API ERROR {e.resp.status}: {e.error_details}")
            if e.resp.status == 403:
                print("!! Quota exhausted — aborting.")
                break
            continue

        except Exception as e:
            print(f"ERROR: {e}")
            continue

    # Sync denormalized metrics
    cur.execute("""
        UPDATE videos
        SET
            views    = (SELECT MAX(views)    FROM video_snapshots WHERE video_snapshots.video_id = videos.video_id),
            likes    = (SELECT MAX(likes)    FROM video_snapshots WHERE video_snapshots.video_id = videos.video_id),
            comments = (SELECT MAX(comments) FROM video_snapshots WHERE video_snapshots.video_id = videos.video_id)
        WHERE video_id IN (SELECT DISTINCT video_id FROM video_snapshots)
    """)
    conn.commit()

    print(f"""
─────────────────────────────
Fetch complete — {fetched_on}
  Videos processed : {total_videos}
  Snapshots written: {total_snapshots}
─────────────────────────────""")

    cur.close()
    conn.close()


if __name__ == "__main__":
    run_fetch()
