# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgh7ELgwtytaOfGZx2ZrPdwBOEJtK5lz
"""

#+++++++++++++++++++++VALIDATION++++++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
import sys
import os
from datetime import datetime
import psycopg2
import psycopg2.extras
import pandas as pd

DB_URL = os.environ.get("NEON_CONNECTION_STRING", "")

def get_conn():
    return psycopg2.connect(DB_URL)

# ============================================================
# CHANNELS TABLE
# ============================================================

def check_channel_number():
    canonical = [
        "UC3njZ48-FDxLleBYaP0SZIg", "UC6RJ7-PaXg6TIH2BzZfTV7w",
        "UCJEDFSxHHOW1PpBccdSxOTA", "UCPgLNge0xqQHWM5B5EFH9Cg",
        "UCQtVJ-76KjPds9evTODkq-A", "UCSaf-7p3J_N-02p7jHzm5tA",
        "UCWCEYVwSqr7Epo6sSCfUgiw", "UCYPvAwZP8pZhSMW8qs7cVCw",
        "UCZFMm1mMw0F81Z37aaEzTUA", "UCc8J8UvzwMZHnO0MX1NTmSw",
        "UCckHqySbfy5FcPP6MD_S-Yg", "UCef1-8eOpJgud7szVPlZQAQ",
        "UChWtJey46brNr7qHQpN6KLQ", "UCl8zB2LZOiLLV0jYUMpTEgA",
        "UCm7lHFkt2yB_WzL67aruVBQ", "UCqTa3sNT6SfiQ2DQK_kuWlA",
        "UCspQie3i29iIFbCgfGisO9Q", "UCustbySVJGb659WDpdkeATg",
        "UCuyRsHZILrU7ZDIAbGASHdA", "UCwqusr8YDwM-3mEYTDeJHzw",
        "UCytSP0M0Jdnw6qIy3Y-nTig"
    ]
    conn = get_conn()
    df = pd.read_sql("SELECT channel_id FROM channels", conn)
    conn.close()
    in_db   = df["channel_id"].tolist()
    missing = [c for c in canonical if c not in in_db]
    extra   = [c for c in in_db if c not in canonical]
    if missing:
        return {"check": "check_channel_number", "status": "FAIL", "detail": f"Missing: {missing}"}
    if extra:
        return {"check": "check_channel_number", "status": "FAIL", "detail": f"Extra: {extra}"}
    return {"check": "check_channel_number", "status": "PASS", "detail": "All 21 channel IDs present."}


def channel_name_validate():
    canonical = [
        "The Wire", "The Quint", "The Print", "NewsLaundry",
        "Oneindia English", "The News Minute", "Scroll.in", "NDTV",
        "India Today", "CNN-News18", "Republic", "Times Now",
        "Mirror Now", "NewsX", "Hindustan Times", "The Telegraph",
        "The Times of India", "Indian Express", "The Tribune",
        "The Hindu", "The New Indian Express"
    ]
    conn = get_conn()
    df = pd.read_sql("SELECT name FROM channels", conn)
    conn.close()
    in_db   = df["name"].tolist()
    missing = [c for c in canonical if c not in in_db]
    extra   = [c for c in in_db if c not in canonical]
    if missing:
        return {"check": "check_channel_name", "status": "FAIL", "detail": f"Missing: {missing}"}
    if extra:
        return {"check": "check_channel_name", "status": "FAIL", "detail": f"Extra: {extra}"}
    return {"check": "check_channel_name", "status": "PASS", "detail": "All 21 channel names correct."}


def subscriber_null_check():
    conn = get_conn()
    df = pd.read_sql("SELECT name FROM channels WHERE subscribers IS NULL", conn)
    conn.close()
    if len(df) > 0:
        return {"check": "subscriber_null_check", "status": "FAIL", "detail": f"{len(df)} NULL subscribers: {df['name'].tolist()}"}
    return {"check": "subscriber_null_check", "status": "PASS", "detail": "No NULL values in subscribers column."}


def date_null_check():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM channels WHERE added_on IS NULL")
    count = cur.fetchone()[0]
    conn.close()
    if count > 0:
        return {"check": "date_added_on_null_check", "status": "FAIL", "detail": f"{count} NULL values in added_on column."}
    return {"check": "date_added_on_null_check", "status": "PASS", "detail": "No NULL values in added_on column in channels table."}


def added_on_format_check():
    # PostgreSQL stores DATE as a proper type — format is always valid if cast succeeds
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM channels WHERE added_on IS NOT NULL")
    count = cur.fetchone()[0]
    conn.close()
    return {"check": "date_added_on_format_check", "status": "PASS", "detail": "All added_on values in channels table are correctly formatted."}


# ============================================================
# VIDEOS TABLE
# ============================================================

def null_check_videos():
    columns = ["video_id", "channel_id", "title", "published_at",
               "duration_seconds", "category", "language", "content_type"]
    query = f"""
        SELECT {", ".join(f"SUM(CASE WHEN {col} IS NULL THEN 1 ELSE 0 END) AS {col}" for col in columns)}
        FROM videos
    """
    conn = get_conn()
    df = pd.read_sql(query, conn)
    conn.close()
    failed = {col: int(df[col][0]) for col in columns if df[col][0] > 0}
    if failed:
        return {"check": "null_check_videos", "status": "FAIL", "detail": f"NULL values found: {failed}"}
    return {"check": "null_check_videos", "status": "PASS", "detail": "No NULL values in required videos columns."}


def null_orphan_chk_videos():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM videos v
        WHERE NOT EXISTS (SELECT 1 FROM channels c WHERE c.channel_id = v.channel_id)
    """)
    orphaned = cur.fetchone()[0]
    conn.close()
    if orphaned == 0:
        return {"check": "orphaned_video", "status": "PASS", "detail": "All videos have a valid channel_id."}
    return {"check": "orphaned_video", "status": "FAIL", "detail": f"{orphaned} videos have no matching channel."}


def null_orphan_chk_snapshot():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM video_snapshots s
        WHERE NOT EXISTS (SELECT 1 FROM videos v WHERE v.video_id = s.video_id)
    """)
    orphaned = cur.fetchone()[0]
    conn.close()
    if orphaned == 0:
        return {"check": "orphaned_video_snapshot", "status": "PASS", "detail": "All snapshots have a valid video_id."}
    return {"check": "orphaned_video_snapshot", "status": "FAIL", "detail": f"{orphaned} snapshots have no matching video."}


def duration_6hrs():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("SELECT COUNT(*) FROM videos WHERE duration_seconds > 21600")
    n = cur.fetchone()[0]
    conn.close()
    if n == 0:
        return {"check": "duration_over_6hrs", "status": "PASS", "detail": "No videos longer than 6 hours."}
    return {"check": "duration_over_6hrs", "status": "WARN", "detail": f"{n} video(s) exceed 6 hours (broadcast_archive expected)."}


def duration_24hrs():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("SELECT video_id, title, duration_seconds FROM videos WHERE duration_seconds > 86400")
    extreme = cur.fetchall()
    conn.close()
    if not extreme:
        return {"check": "duration_over_24hrs", "status": "PASS", "detail": "No videos longer than 24 hours."}
    return {"check": "duration_over_24hrs", "status": "FAIL", "detail": f"{len(extreme)} video(s) exceed 24 hours: {[(r[0], r[1]) for r in extreme]}"}


def zero_view_check():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM video_snapshots s
        JOIN videos v ON s.video_id = v.video_id
        WHERE s.views = 0
        AND v.content_type != 'live_or_premiere'
    """)
    zero_views = cur.fetchone()[0]
    conn.close()
    if zero_views == 0:
        return {"check": "zero_view_check", "status": "PASS", "detail": "No zero-view snapshots (excluding live/premiere)."}
    return {"check": "zero_view_check", "status": "FAIL", "detail": f"{zero_views} non-live snapshot(s) have 0 views."}


def missing_videos():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT c.name FROM channels c
        WHERE NOT EXISTS (SELECT 1 FROM videos v WHERE v.channel_id = c.channel_id)
    """)
    missing = cur.fetchall()
    conn.close()
    if missing:
        return {"check": "channels_with_no_videos", "status": "FAIL", "detail": f"Channels with 0 videos: {[r[0] for r in missing]}"}
    return {"check": "channels_with_no_videos", "status": "PASS", "detail": "All 21 channels have at least 1 video."}


# ============================================================
# ADDITIONAL CHECKS
# ============================================================

def content_type_values_check():
    allowed = {"regular", "short", "live_or_premiere", "livestream", "broadcast_archive"}
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("SELECT DISTINCT content_type FROM videos")
    found = {r[0] for r in cur.fetchall()}
    conn.close()
    invalid = found - allowed
    if invalid:
        return {"check": "content_type_values_check", "status": "FAIL", "detail": f"Unexpected content_type values: {invalid}"}
    return {"check": "content_type_values_check", "status": "PASS", "detail": f"All content_type values are valid: {found}"}


def duplicate_video_id_check():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM (
            SELECT video_id FROM videos GROUP BY video_id HAVING COUNT(*) > 1
        ) dupes
    """)
    n = cur.fetchone()[0]
    conn.close()
    if n > 0:
        return {"check": "duplicate_video_id_check", "status": "FAIL", "detail": f"{n} duplicate video_id(s) in videos table."}
    return {"check": "duplicate_video_id_check", "status": "PASS", "detail": "No duplicate video_ids."}


def duplicate_snapshot_check():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM (
            SELECT video_id, fetched_on FROM video_snapshots
            GROUP BY video_id, fetched_on HAVING COUNT(*) > 1
        ) dupes
    """)
    n = cur.fetchone()[0]
    conn.close()
    if n > 0:
        return {"check": "duplicate_snapshot_check", "status": "FAIL", "detail": f"{n} duplicate (video_id, fetched_on) pairs in video_snapshots."}
    return {"check": "duplicate_snapshot_check", "status": "PASS", "detail": "No duplicate snapshots."}


def future_published_at_check():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute(
        "SELECT COUNT(*) FROM videos WHERE published_at > %s",
        (datetime.utcnow().isoformat(),)
    )
    n = cur.fetchone()[0]
    conn.close()
    if n > 0:
        return {"check": "future_published_at_check", "status": "FAIL", "detail": f"{n} video(s) have a future published_at."}
    return {"check": "future_published_at_check", "status": "PASS", "detail": "No future-dated published_at values."}


def views_regression_check():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM (
            SELECT s1.video_id
            FROM video_snapshots s1
            JOIN video_snapshots s2
              ON s1.video_id = s2.video_id AND s1.fetched_on < s2.fetched_on
            WHERE s2.views < s1.views - 10
        ) regressions
    """)
    n = cur.fetchone()[0]
    conn.close()
    if n > 0:
        return {"check": "views_regression_check", "status": "WARN", "detail": f"{n} video(s) show a meaningful decrease in views (>10) across snapshots."}
    return {"check": "views_regression_check", "status": "PASS", "detail": "No meaningful view count regressions detected."}


def videos_without_snapshots_check():
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT COUNT(*) FROM videos v
        WHERE NOT EXISTS (SELECT 1 FROM video_snapshots s WHERE s.video_id = v.video_id)
    """)
    n = cur.fetchone()[0]
    conn.close()
    if n > 0:
        return {"check": "videos_without_snapshots_check", "status": "FAIL", "detail": f"{n} video(s) have no snapshot."}
    return {"check": "videos_without_snapshots_check", "status": "PASS", "detail": "All videos have at least one snapshot."}


# ============================================================
# RUNNER
# ============================================================

HARD_FAIL = {"FAIL"}
SOFT_WARN = {"WARN"}

def run_all():
    results = [
        check_channel_number(),
        channel_name_validate(),
        subscriber_null_check(),
        date_null_check(),
        added_on_format_check(),
        null_check_videos(),
        null_orphan_chk_videos(),
        null_orphan_chk_snapshot(),
        duration_6hrs(),
        duration_24hrs(),
        zero_view_check(),
        missing_videos(),
        content_type_values_check(),
        duplicate_video_id_check(),
        duplicate_snapshot_check(),
        future_published_at_check(),
        views_regression_check(),
        videos_without_snapshots_check(),
    ]

    passes   = [r for r in results if r["status"] == "PASS"]
    warnings = [r for r in results if r["status"] == "WARN"]
    failures = [r for r in results if r["status"] == "FAIL"]

    print(f"VALIDATION SUMMARY: {len(passes)} passed / {len(warnings)} warnings / {len(failures)} failed")

    for r in results:
        icon = "✓" if r["status"] == "PASS" else ("⚠" if r["status"] == "WARN" else "✗")
        print(f"  [{icon}] {r['check']}: {r['detail']}")

    if warnings:
        print(f"\n  {len(warnings)} warning(s) logged — pipeline continues.")

    if failures:
        print(f"\n{'='*60}")
        print("PIPELINE HALTED — fix the above failures before proceeding.")
        print(f"{'='*60}\n")
        sys.exit(1)

    print("\nAll checks passed. Pipeline is clear to proceed.\n")


if __name__ == "__main__":
    run_all()